language: generic
addons:
   hosts:
       - travis
   hostname: travis
env:
   - PYTHON_VERSION="2.7" DEPLOY_DOCS=true
   - PYTHON_VERSION="3.5"
before_install:
   # If `$DEPLOY_DOCS` is unset, make it `false` by default.
   - if [ -z $DEPLOY_DOCS ]; then DEPLOY_DOCS=false; fi
   # Get the tag if it wasn't provided. Travis doesn't provide this if it isn't a tagged build.
   - if [ -z $TRAVIS_TAG ]; then TRAVIS_TAG=`git tag --contains` ; fi
   - echo $TRAVIS_TAG
   # Move out of git directory to build root.
   - cd ../..
   - pwd
install:
   # Download and configure conda.
   - wget http://repo.continuum.io/miniconda/Miniconda`echo ${PYTHON_VERSION:0:1}`-latest-Linux-x86_64.sh -O miniconda.sh
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - conda config --set always_yes yes
   - conda config --set show_channel_urls True
   - conda config --add channels conda-forge
   - source activate root
   - conda update --all
   # Fix root environment to have the correct Python version.
   - touch $HOME/miniconda/conda-meta/pinned
   - echo "python ${PYTHON_VERSION}.*" >> $HOME/miniconda/conda-meta/pinned
   - conda install python=$PYTHON_VERSION
   # Install basic conda dependencies.
   - conda install conda-build
   # Build the conda package for splauncher.
   - cd $TRAVIS_REPO_SLUG
   - VERSION=`python setup.py --version`
   - echo $VERSION
   - python setup.py bdist_conda
   # Setup environment for splauncher and install it with all dependencies.
   - conda create --use-local -n testenv python=$PYTHON_VERSION splauncher==$VERSION
   - source activate testenv
   # Install DRMAA with Python support.
   - .travis_scripts/install_sge.sh
   - export SGE_ROOT=/var/lib/gridengine
   - export SGE_CELL=default
   - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
   - conda install drmaa
   # Install sphinx 1.3 and friends to build documentation.
   - echo "sphinx 1.3.*" >> $HOME/miniconda/envs/testenv/conda-meta/pinned
   - conda install sphinx
   - conda install cloud_sptheme
   # Install coverage and coveralls to generate and submit test coverage results for coveralls.io.
   # Also, install docstring-coverage to get information about documentation coverage.
   - conda install nose-timer
   - echo "coverage 3.*" >> $HOME/miniconda/envs/testenv/conda-meta/pinned
   - conda install coverage
   - conda install docstring-coverage || true
   - conda install python-coveralls
   # Clean up downloads as there are quite a few and they waste space/memory.
   - sudo apt-get clean
   - conda clean -tipsy
   - rm -rfv $HOME/.cache/pip
script:
   # Run tests. Skip 3D tests as they take too long (~1hr).
   - python setup.py nosetests --with-timer
   # Build documentation.
   - python setup.py build_sphinx
   # Get info on docstring coverage.
   - (hash docstring-coverage && docstring-coverage nanshe | tee .docstring-coverage) || true
after_success:
   # Submit results to coveralls.io.
   - coveralls
   # Check to see if this is the right branch to build documentation from.
   - if [ $TRAVIS_PULL_REQUEST != "false" ] || [ $TRAVIS_REPO_SLUG != "jakirkham/splauncher" ] || [ $TRAVIS_BRANCH != "master" ]; then exit 0 ; fi
   # Save documentation and documentation coverage statistics.
   - mv build/sphinx/html ../splauncher-git-docs
   - mv .docstring-coverage ../splauncher-git-docs
   # Update credentials
   - git config --global user.name "Travis CI"
   - git config --global user.email "noreply@travis-ci.org"
   # Get current pages. Unfortunately, `git fetch` does not work here.
   - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
   - git checkout --orphan gh-pages
   - git pull origin gh-pages
   - git branch -v
   # Save important git files.
   - mv .git ../splauncher-git-docs/
   - mv .nojekyll ../splauncher-git-docs/
   # Replace old documentation with new documentation.
   - rm -rf * .*
   - mv ../splauncher-git-docs/.nojekyll .
   - mv ../splauncher-git-docs/.git .
   - mv ../splauncher-git-docs/.docstring-coverage .
   - mv ../splauncher-git-docs/* .
   - rm -rf ../splauncher-git-docs
   # Commit changes and push. Reference commit used and tag if relevant.
   - git add -A
   - if [ -z $TRAVIS_TAG ]; then git commit -m "Rebuilt documentation for commit (${TRAVIS_COMMIT})." --allow-empty ; else git commit -m "Rebuilt documentation for commit (${TRAVIS_COMMIT}) and tag (${TRAVIS_TAG})." --allow-empty ; fi
   - $DEPLOY_DOCS && (git push -q origin gh-pages > /dev/null 2>&1; echo $?)
   # Check to see if this is a release. If so, create and upload binaries.
   - if [ -z $TRAVIS_TAG ]; then exit 0 ; fi
   - git checkout $TRAVIS_TAG
   - source activate root
   - conda install anaconda-client
   - cd $HOME/miniconda/conda-bld/
   - conda convert -p osx-64 linux-64/splauncher*
   - conda server -t ${AS_TOKEN} upload linux-64/splauncher*
   - conda server -t ${AS_TOKEN} upload osx-64/splauncher*
notifications:
  email:
    - $TO_EMAIL
# Use container format for TravisCI to avoid termination due to insufficient resources.
#sudo: false
